site_name: Markdown Manuals for Bioinformatics Training Platform (BTP)
site_description: This contains all material for Markdown version of BTP workshops.
site_author: Authors

#site_url: 'https://bpa-csiro-workshops.github.io/metagenomics-manuals'

copyright: '&copy; The authors; 2017-'

#Documentation and theme
theme: material

# Options
extra:
  palette:
    primary: 'indigo'
    accent: 'light blue'

  feature:
    tabs: true

  site_favicon: 'media/logos/Bioplatforms-Australia-favicon2.png'

markdown_extensions:
    - admonition
    - smarty
    - tables
    - markdown_include.include
    - codehilite(linenums=True)
#    - codehilite
    - toc(permalink=true)
    - mdx_math
    - pymdownx.betterem(smart_enable=all)
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist(custom_checkbox=true)
    - pymdownx.tilde
    - pymdownx.details

extra_css:
    #- css/extra.css
    - css/details.css

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    - js/details.js

pages:
- Home: index.md
- The Trainers: trainers/trainers.md
- Timetable:
  - Metagenomics: timetables/timetable_metagenomics.md
- Workshop Information: preamble.md

# - All Modules:
#     - Metagenomics Functional Analysis:
#         - Functional Analysis using EMG: modules/metagenomics-module-fda/fda.md
#     - Metagenomics mining EMG with R:
#         - Mining EMG with R part 1: modules/metagenomics-module-emgr/emgr-part1.md
#         - Mining EMG with R part 2A: modules/metagenomics-module-emgr/emgr-part2A.md
#         - Mining EMG with R part 2B: modules/metagenomics-module-emgr/emgr-part2B.md
#     - Metagenomics Data Quality: modules/metagenomics-module-qc/ngs-qc.md
#     - Metagenomics Taxonomic : modules/metagenomics-module-tax/tax.md
#     - Metagenomics Visualisation: modules/metagenomics-module-vis/vis.md
#     - Metagenomics WGA: modules/metagenomics-module-wga/wga.md

- Metagenomics Modules:
    - Metagenomics QC: modules/metagenomics-module-qc/ngs-qc.md
    - Metagenomics Taxonomic: modules/metagenomics-module-tax/tax.md
    - Metagenomics mining EMG with R:
        - Mining EMG with R part 1: modules/metagenomics-module-emgr/emgr-part1.md
        - Mining EMG with R part 2A: modules/metagenomics-module-emgr/emgr-part2A.md
        - Mining EMG with R part 2B: modules/metagenomics-module-emgr/emgr-part2B.md
    - Metagenomics WGA: modules/metagenomics-module-wga/wga.md
    - Metagenomics Functional Analysis: modules/metagenomics-module-fda/fda.md
